### ISSUE TITLE
CSV support

### ISSUE THREAD

**Issue by joaquincasares** [jshook/metagener#4]
Ability for metagener to not only parse CSV files, but to relate data across the row.

Example scenario: stock symbol, last trade, market cap.

I'd want the values to all be related. 

I'd also want the stock symbol and market caps to stay static, while the last trade would vary from some point starting with the initial trade.

**Comment by joaquincasares** [comment]
An additional use case here would reading zip codes from a file.

When the generator generates a city for me, I'll receive a city, state, and zip code.

**Comment by jshook** [comment]
This is now implemented as csvfilesample(file,field,dist). With no adjustments, generators on the same file and dist will align the selected row. (Each columnar slice of the CSV is prepared for a specific entity field)
Bear in mind that distributions besides 'uniform' are not yet supported.
